### ISSUE TITLE
Error taking backup on file open:  This BackgroundWorker is currently busy

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#142]
**Describe the bug**
Following a successful open outline open (with backup on open), closing the outline and opening another will create an error
on the file open backup. 

**To Reproduce**
1. Launch StoryBuilder and open an outline, for example, sample Rocky.stbx. The outline will successfully open.
2. Close the outline.
3. Open another outline (it doesn't matter which one.) For example, sample Hamlet.stbx. (Could even be Rocky again.) The outline will successfully open, but StatusMessage will show 'Error in OpenFile command', and examining the log will display an exception relating to the file open backup. Here's the log excerpt:

2022-01-23 02:17:51.0819 | Info | Reading file C:\temp\samples\Rocky.stbx. | 
2022-01-23 02:17:51.2235 | Info | File load successful. | 
2022-01-23 02:17:51.2235 | Info | Starting Project Backup | 
2022-01-23 02:17:51.2512 | Info | Backing up to C:\Users\tcox\Documents\Writing\Backup\Rocky.stbx as Rocky as of 1 23 2022 2 17 51 AM.zip | 
2022-01-23 02:17:51.3048 | Info | Created Zip file at C:\Users\tcox\Documents\Writing\Backup\Rocky.stbx\Rocky as of 1 23 2022 2 17 51 AM.zip | 
2022-01-23 02:17:51.4526 | Info | Finished backup. | 
2022-01-23 02:17:51.4526 | Info | BackupProject complete | 
2022-01-23 02:17:51.4526 | Info | Updating prf from model. | 
2022-01-23 02:17:51.4526 | Info | Opened project Rocky.stbx | 
2022-01-23 02:17:51.4526 | Info | Open Story completed. | 
2022-01-23 02:17:51.4526 | Info | Timed backup task started. | 
2022-01-23 02:17:56.6602 | Info | Executing Close project command | 
2022-01-23 02:17:56.6602 | Info | ShowHomePage | 
2022-01-23 02:17:56.6602 | Info | Close story command completed | 
2022-01-23 02:18:03.1721 | Info | Executing OpenFile command | 
2022-01-23 02:18:05.4204 | Info | Reading file C:\temp\samples\Hamlet.stbx. | 
2022-01-23 02:18:05.4788 | Info | File load successful. | 
2022-01-23 02:18:05.4788 | Info | Starting Project Backup | 
2022-01-23 02:18:05.4960 | Info | Backing up to C:\Users\tcox\Documents\Writing\Backup\Hamlet.stbx as Hamlet as of 1 23 2022 2 18 05 AM.zip | 
2022-01-23 02:18:05.5351 | Info | Created Zip file at C:\Users\tcox\Documents\Writing\Backup\Hamlet.stbx\Hamlet as of 1 23 2022 2 18 05 AM.zip | 
2022-01-23 02:18:05.6879 | Info | Finished backup. | 
2022-01-23 02:18:05.6879 | Info | BackupProject complete | 
2022-01-23 02:18:05.6879 | Info | Updating prf from model. | 
2022-01-23 02:18:05.6879 | Error | Error in OpenFile command | This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.    at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
   at System.ComponentModel.BackgroundWorker.RunWorkerAsync()
   at StoryBuilder.Services.BackupService.StartTimedBackup()
   at StoryBuilder.ViewModels.ShellViewModel.OpenFile(String fromPath)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by terrycox** [comment]
Closed by merge
