### ISSUE TITLE
splitview content persists in new story

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryBuilder-2#181]
**Describe the bug**
When a story is created whilst one is open the content of the old story persists

**To Reproduce**
1. Open story and then open a node
2. Make a new story
3. Old stuff will persist
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49795711/155786167-fbff6f75-39fb-41f3-a782-6685697c722f.png)

**Additional context**
Implications of this bug are unknown.

**Comment by henley352** [comment]
I need a little mores info on what I should expect to see & or steps to test- thanks

**Comment by henley352** [comment]
Discussed with Jake - advised 
The sideview will now be reset when a new story is loaded.  requested add' info from Jake for testing - Testing in progress - For the spitview stuff
1) load a story and click a node
2) load a different story
3) if the content persists then its broken

**Comment by henley352** [comment]
Discussed with Terry, here's what the logs say about #181:
2022-03-02 05:14:11.8991 | Info | TreeViewNodeClicked for Rocky                                      | 
2022-03-02 05:14:16.3237 | Info | TreeViewNodeClicked for Credits scene | 
2022-03-02 05:14:16.3378 | Warn | ViewpointCharacterTip displayed | 
2022-03-02 05:14:19.1957 | Info | TreeViewNodeClicked for Rocky                                      | 
2022-03-02 05:14:26.4778 | Info | TreeViewNodeClicked for Credits scene | 
2022-03-02 05:15:03.4110 | Error | Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled. | Catastrophic failure (0x8000FFFF (E_UNEXPECTED)) Description: ;RestrictedDescription: ;RestrictedErrorReference: ;RestrictedCapabilitySid: ;RestrictedErrorObjectReference: ;HasRestrictedLanguageErrorObject: False
2022-03-02 05:15:06.9983 | Error | Error navigating in TreeViewNodeClicked | Object reference not set to an instance of an object.    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>gThrow|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrame.global::Microsoft.UI.Xaml.Controls.IFrame.Navigate(Type sourcePageType, Object parameter)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
   at StoryBuilder.Services.Navigation.NavigationService.NavigateTo(Frame frame, String pageKey, Object parameter)
   at StoryBuilder.ViewModels.ShellViewModel.TreeViewNodeClicked(Object selectedItem) Description: The object has been closed.
;RestrictedDescription: The given object has already been closed / disposed and may no longer be used.;RestrictedErrorReference: ;RestrictedCapabilitySid: ;RestrictedErrorObjectReference: WinRT.ExceptionHelpers+RestrictedErrorObject;HasRestrictedLanguageErrorObject: False
The exception logging level should be 'Fatal', not 'Error'; the program crashes
What's going on here is that when you click on a TreeView node, the program navigates to the Page for that node type, which is what displays the right-hand-side of the screen
It passes the correct piece of the story model when it does so. The navigation also involves saving the previous node's state into the model before it does so

Possibility:  it navigates to the Overview node before the outline is fully loaded.
