### ISSUE TITLE
Error message issues with Open or new file

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#338]
5eDescribe the bug
error message states - right click on node.  Node is not showing.

1. Open existing story - The Glass Menagerie
2. From title bar (reports),  select new file/open new file
3. Error:  error message (in red) states Open Story command failed

![image](https://user-images.githubusercontent.com/21226407/171497860-1d6d8f07-b152-44c4-a7fd-e81ab78e064f.png)

4.   Select + sign add new folder
5.   Receive error in yellow.  
![image](https://user-images.githubusercontent.com/21226407/171498431-e6f779e6-4326-486a-8407-eff389536244.png)

7. **Expected behavior**
user should be able to add folder or a clear reason why not should show.
2022-06-01 16:33:38.0955 | Error | Error in OpenFile command | Object reference not set to an instance of an object.    at StoryBuilder.ViewModels.ShellViewModel.OpenFile(String fromPath)
2022-06-01 16:33:38.1171 | Error | Open Story command failed | 
2022-06-01 16:33:38.1171 | Info | Open Story completed. | 
2022-06-01 16:33:39.2920 | Error | Error in OpenFile command | Object reference not set to an instance of an object.    at StoryBuilder.ViewModels.ShellViewModel.OpenFile(String fromPath)
2022-06-01 16:33:39.2920 | Error | Open Story command failed | 
2022-06-01 16:33:39.2920 | Info | Open Story completed. | 
**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/171498902-a4390a7d-d388-49b5-80c8-d32dc2b2ecf2.png)

**Additional context**

**Comment by henley352** [comment]
[updater.2022-06-01.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8818683/updater.2022-06-01.log)

**Comment by Rarisma** [comment]
It seems that the story failed to open and you didn't realise you can't add nodes with no story loaded.
With no information to go on about this failure, I think I might have solved this issue but regardless this issue should be closed as its a user error.
