### ISSUE TITLE
Fatal error installing Webview

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#454]
**Describe the bug**
From elmah.io:

An async operation was not properly started. (0x80000019)

Time    12/2/2022 10:12:21 AM
Severity        Fatal
URL
Method
Status Code
Host    LAPTOP-O6PR5OGM
Error   System.Runtime.InteropServices.COMException
Application
Source  at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

User    Sean Fager(SeanFager@OUTLOOK.com)
Version Version: 2.5.0.0

System.Runtime.InteropServices.COMException (0x80000019): An async operation was not properly started.      

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
Log data from elmah.io:

2022-12-02 07:02:25.2351 | Info | Post user preferences to back-end database |
2022-12-02 07:02:27.8541 | Info | Back-end database connection ended |
2022-12-02 07:02:27.8541 | Info | Posting version data to parse |
2022-12-02 07:02:28.0332 | Info | Back-end database connection ended |
2022-12-02 07:02:28.0332 | Info | Version mismatch: Version: 2.5.0.0 != |
2022-12-02 07:02:28.0332 | Info | Updating prf from model. |
2022-12-02 07:02:28.1742 | Info | Posting version data to parse |
2022-12-02 07:02:28.2446 | Info | Back-end database connection ended |
2022-12-02 07:02:29.2450 | Info | Loading Controls.ini data |
2022-12-02 07:02:29.3247 | Info | ConflictType Counts |
2022-12-02 07:02:29.3247 | Info | 6 ConflictType keys created |
2022-12-02 07:02:29.3247 | Info | 62 Total ConflictSubType keys created |
2022-12-02 07:02:29.3247 | Info | 220 Total ConflictSubType keys created |
2022-12-02 07:02:29.3346 | Info | Loading Lists.ini data |
2022-12-02 07:02:29.3539 | Info | 65 ListLoader.Init keys created |
2022-12-02 07:02:29.3539 | Info | Loading Tools.ini data |
2022-12-02 07:02:29.4524 | Info | 5 Key Questions created |
2022-12-02 07:02:29.4524 | Info | 11 Stock Scenes created |
2022-12-02 07:02:29.4524 | Info | 9 Topics created |
2022-12-02 07:02:29.4524 | Info | 22 Master Plots created |
2022-12-02 07:02:29.4524 | Info | 36 Dramatic Situations created |
2022-12-02 07:02:29.4524 | Info | Configuring page navigation |
2022-12-02 07:02:30.8246 | Info | StoryBuilder App loaded and launched |
2022-12-02 07:10:17.3085 | Info | Updating prf from model. |
2022-12-02 07:10:17.9307 | Info | Ready |
2022-12-02 07:10:18.1191 | Warn | You need to load a story first! |
2022-12-02 07:10:18.1191 | Info | Failed to switch views as DataSource is null or empty. (Is a story loaded?) |
2022-12-02 07:10:18.5191 | Info | ShowHomePage |
2022-12-02 07:10:18.5329 | Info | Connection established |
2022-12-02 07:10:18.5329 | Info | Connection established |
2022-12-02 07:10:18.5983 | Error | Showing webview install dialog. |
2022-12-02 07:10:18.9959 | Info | PreferencesModel updated from StoryBuilder.prf. |
2022-12-02 07:10:18.9959 | Info | Post user preferences to back-end database |
2022-12-02 07:10:19.3101 | Info | Name: Sean Fager userId: 220 |
2022-12-02 07:10:19.3293 | Info | Updating prf from model. |
2022-12-02 07:10:19.7409 | Info | Preferences: elmah=True newsletter=True |
2022-12-02 07:10:19.7409 | Info | Back-end database connection ended |
2022-12-02 07:10:25.7536 | Error | User clicked Primary |
2022-12-02 07:10:25.7536 | Error | Installing webview... |
2022-12-02 07:12:20.5459 | Info | Webview installed |
2022-12-02 07:12:21.0304 | Fatal | An async operation was not properly started. (0x80000019) | An async operation was not properly started. (0x80000019) at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at StoryBuilder.ViewModels.WebViewModel.InstallWebview()
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0() Description: An async operation was not properly started.
;RestrictedDescription: Only a single ContentDialog can be open at any time.;RestrictedErrorReference: ;RestrictedCapabilitySid: ;__RestrictedErrorObjectReference: WinRT.ExceptionHelpers+__RestrictedErrorObject;__HasRestrictedLanguageErrorObject: False

**Comment by terrycox** [comment]
Closed via PR #456
