### ISSUE TITLE
Specified cast is not valid in WriteModel()

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#461]
**Describe the bug**
Specified cast is not valid in WriteModel()

elmah.io log data:
Time: Dec 15, 2022 11:02:12AM
Severity: Error
Host: DYLANS-DESKTOP
Source: System.InvalidCastException: Specified cast is not valid.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.Storage.ICachedFileManagerStaticsMethods.DeferUpdates(IObjectReference _obj, IStorageFile file)
   at Windows.Storage.CachedFileManager.DeferUpdates(IStorageFile file)
   at StoryBuilder.ViewModels.ShellViewModel.WriteModel()
User:  Dylan Simmons(percussion97@gmail.com
Version: 2.5.1.0

**Expected behavior**

**Screenshots**

**Additional context**
Log information:
2022-12-15 10:01:29.7858 | Info | Loading Lists.ini data |
2022-12-15 10:01:29.7858 | Info | 65 ListLoader.Init keys created |
2022-12-15 10:01:29.7858 | Info | Loading Tools.ini data |
2022-12-15 10:01:29.8231 | Info | 5 Key Questions created |
2022-12-15 10:01:29.8231 | Info | 11 Stock Scenes created |
2022-12-15 10:01:29.8231 | Info | 9 Topics created |
2022-12-15 10:01:29.8231 | Info | 22 Master Plots created |
2022-12-15 10:01:29.8231 | Info | 36 Dramatic Situations created |
2022-12-15 10:01:29.8231 | Info | Configuring page navigation |
2022-12-15 10:01:30.1455 | Info | StoryBuilder App loaded and launched |
2022-12-15 10:01:32.6096 | Info | Back-end database connection ended |
2022-12-15 10:01:32.6096 | Info | Posting version data to parse |
2022-12-15 10:01:34.5587 | Info | Back-end database connection ended |
2022-12-15 10:01:34.5587 | Info | Version mismatch: Version: 2.5.1.0 != |
2022-12-15 10:01:34.5587 | Info | Updating prf from model. |
2022-12-15 10:01:34.6144 | Info | Posting version data to parse |
2022-12-15 10:01:34.7241 | Info | Back-end database connection ended |
2022-12-15 10:01:47.6101 | Info | Updating prf from model. |
2022-12-15 10:01:47.7217 | Info | Ready |
2022-12-15 10:01:47.7702 | Warn | You need to load a story first! |
2022-12-15 10:01:47.7702 | Info | Failed to switch views as DataSource is null or empty. (Is a story loaded?) |
2022-12-15 10:01:47.8217 | Info | ShowHomePage |
2022-12-15 10:01:47.8217 | Info | Connection established |
2022-12-15 10:01:47.8217 | Info | Connection established |
2022-12-15 10:01:47.8911 | Info | PreferencesModel updated from StoryBuilder.prf. |
2022-12-15 10:01:47.8911 | Info | Post user preferences to back-end database |
2022-12-15 10:01:48.2528 | Info | Name: Dylan Simmons userId: 239 |
2022-12-15 10:01:48.2924 | Info | Updating prf from model. |
2022-12-15 10:01:48.3075 | Info | Preferences: elmah=True newsletter=True |
2022-12-15 10:01:48.3075 | Info | Back-end database connection ended |
2022-12-15 10:02:11.8971 | Info | Updating prf from model. |
2022-12-15 10:02:11.8971 | Info | FileOpenVM - New File starting |
2022-12-15 10:02:11.8971 | Info | New project command executing |
2022-12-15 10:02:11.9383 | Info | Updating prf from model. |
2022-12-15 10:02:11.9383 | Info | Executing SaveFile command |
2022-12-15 10:02:11.9383 | Info | Save File command executing |
2022-12-15 10:02:11.9407 | Info | In WriteModel, file=Cinema Inferno.stbx |
2022-12-15 10:02:12.1660 | Error | Error writing file | Specified cast is not valid. at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
at ABI.Windows.Storage.ICachedFileManagerStaticsMethods.DeferUpdates(IObjectReference _obj, IStorageFile file)
at Windows.Storage.CachedFileManager.DeferUpdates(IStorageFile file)
at StoryBuilder.ViewModels.ShellViewModel.WriteModel() Description: No such interface supported
;RestrictedDescription: No such interface supported
;RestrictedErrorReference: ;RestrictedCapabilitySid: ;__RestrictedErrorObjectReference: WinRT.ExceptionHelpers+__RestrictedErrorObject;__HasRestrictedLanguageErrorObject: False
2022-12-15 10:02:12.1754 | Error | Error writing file - see log |
2022-12-15 10:02:12.1754 | Info | Save File command completed |
2022-12-15 10:02:12.1754 | Info | SaveFile completed |
2022-12-15 10:02:12.1754 | Info | New project command executing |
2022-12-15 10:02:12.1754 | Info | New project command executing |
2022-12-15 10:02:12.1754 | Info | Timed backup task started. |

**Comment by terrycox** [comment]
A writeup on cache manager:
https://learn.microsoft.com/en-us/uwp/api/windows.storage.cachedfilemanager?view=winrt-22621
 I've emailed Mr. Simmons asking for more details. The email's attached.
[Error writing StoryBuilder file.zip](https://github.com/storybuilder-org/StoryBuilder-2/files/10252233/Error.writing.StoryBuilder.file.zip)
This query:
WINUI 3 EXCEPTION Windows.Storage.CachedFileManager.DeferUpdates(IStorageFile file)
led to this:
https://stackoverflow.com/questions/32055653/uwp-winrt-when-calling-cachedfilemangerdeferupdates-getting-access-denied-on

**Comment by terrycox** [comment]
Closed by PR #476 (I think)
