### ISSUE TITLE
Error navigating in ShellVM.TreeViewNodeClicked

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#493]
**Describe the bug**
Time: Sunday, February 5, 2023 2:01:36 PM
Severity: Error
Host: LAPTOP-9RITOGMA
Source: System.Collections.Generic.KeyNotFoundException
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at StoryBuilder.ViewModels.ShellViewModel.TreeViewNodeClicked(Object selectedItem)
User: shontell weaver(shontellweaver0824!@gmail.com)
Version: Version: 2.6.0.0

**To Reproduce**

**Expected behavior**

**Screenshots**
N/A

**Additional context**
Emailing user asking for more info or .stbx file.
Log: 
[Navigation error on TreeViewNodeClicked.txt](https://github.com/storybuilder-org/StoryBuilder-2/files/10673758/Navigation.error.on.TreeViewNodeClicked.txt)

**Comment by terrycox** [comment]
Contacted the user, who said she only created the file and tried to open it.
I've done the same on OneDrive with no problems.

Investigating the 'Restricted access' error message.

**Comment by terrycox** [comment]
Investigating the 0xC00Ce558 error, it appears that this may be because the .stbx file is empty. In other words, the error isn't in reading the file, but back when it was written.  

Further investigation suggests that the XmlWriter Stream approach, after calling XmlDocument.Save(), may need to 
flush the Stream before closing it. I've added a .FlushAsync() call.
